name: faults
channels:
  - conda-forge
  - pyviz
  - defaults
dependencies:
  - numpy=1.18.1
  - panel=0.9.5
  - param=1.9.3
  - python=3.7.7
  - scipy=1.4.1
  - scikit-image=0.16.2
packages:
- jupyter_panel_proxy
  