name: holoviz-tutorial
channels:
  - conda-forge
  - pyviz
  - defaults
dependencies:
  - appnope=0.1.0=py37_0
  - asn1crypto=1.3.0=py37_0
  - attrs=19.3.0=py_0
  - backcall=0.1.0=py37_0
  - blas=1.0=mkl
  - bleach=3.1.4=py_0
  - bokeh=2.0.2=py37_0
  - bzip2=1.0.8=h1de35cc_0
  - ca-certificates=2020.1.1=0
  - certifi=2020.4.5.1=py37_0
  - cffi=1.14.0=py37hb5b8e2f_0
  - cftime=1.1.2=py37h776bbcc_0
  - chardet=3.0.4=py37_1003
  - click=7.1.1=py_0
  - cloudpickle=1.4.1=py_0
  - colorcet=2.0.2=py_0
  - cryptography=2.8=py37ha12b0ac_0
  - curl=7.69.1=ha441bb4_0
  - cycler=0.10.0=py37_0
  - cytoolz=0.10.1=py37h1de35cc_0
  - dask=2.15.0=py_0
  - dask-core=2.15.0=py_0
  - datashader=0.10.0=py_0
  - datashape=0.5.4=py37_1
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - distributed=2.15.2=py37_0
  - entrypoints=0.3=py37_0
  - fastparquet=0.3.2=py37h1d22016_0
  - freetype=2.9.1=hb4e5f40_0
  - fsspec=0.7.1=py_0
  - hdf4=4.2.13=h39711bb_2
  - hdf5=1.10.4=hfa1e0ec_0
  - heapdict=1.0.1=py_0
  - holoviews=1.13.2=py_0
  - holoviz=0.11.3=py_0
  - hvplot=0.5.2=py_1
  - idna=2.9=py_1
  - imageio=2.8.0=py_0
  - importlib_metadata=1.5.0=py37_0
  - intel-openmp=2019.4=233
  - ipykernel=5.1.4=py37h39e3cac_0
  - ipython=7.13.0=py37h5ca1d4c_0
  - ipython_genutils=0.2.0=py37_0
  - ipywidgets=7.5.1=py_0
  - jedi=0.17.0=py37_0
  - jinja2=2.11.2=py_0
  - jpeg=9b=he5867d9_2
  - json5=0.9.4=py_0
  - jsonschema=3.2.0=py37_0
  - jupyter_client=6.1.3=py_0
  - jupyter_core=4.6.3=py37_0
  - jupyterlab=1.2.6=pyhf63ae98_0
  - jupyterlab_server=1.1.1=py_0
  - jupyter-panel-proxy
  - kiwisolver=1.2.0=py37h04f5b5a_0
  - krb5=1.17.1=hddcf347_0
  - libcurl=7.69.1=h051b688_0
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h0a44026_6
  - libgfortran=3.0.1=h93005f0_2
  - libnetcdf=4.7.3=he3b6227_0
  - libpng=1.6.37=ha441bb4_0
  - libsodium=1.0.16=h3efe00b_0
  - libssh2=1.9.0=ha12b0ac_1
  - libtiff=4.1.0=hcb84e12_0
  - llvmlite=0.32.0=py37h8c7ce04_0
  - locket=0.2.0=py37_1
  - markdown=3.1.1=py37_0
  - markupsafe=1.1.1=py37h1de35cc_0
  - matplotlib=3.0.3=py37h54f8f79_0
  - matplotlib-base=3.1.3=py37h9aa3819_0
  - mistune=0.8.4=py37h1de35cc_0
  - mkl=2019.4=233
  - mkl-service=2.3.0=py37hfbe908c_0
  - mkl_fft=1.0.15=py37h5e564d8_0
  - mkl_random=1.1.0=py37ha771720_0
  - msgpack-python=1.0.0=py37h04f5b5a_1
  - multipledispatch=0.6.0=py37_0
  - nbconvert=5.6.1=py37_0
  - nbformat=5.0.4=py_0
  - ncurses=6.2=h0a44026_1
  - netcdf4=1.5.3=py37h28545a2_0
  - networkx=2.4=py_0
  - nodejs=6.13.1=0
  - notebook=6.0.3=py37_0
  - numba=0.49.0=py37h6c726b0_0
  - numpy=1.18.1=py37h7241aed_0
  - numpy-base=1.18.1=py37h6575580_1
  - olefile=0.46=py37_0
  - openssl=1.1.1g=h1de35cc_0
  - packaging=20.3=py_0
  - pandas=0.24.2=py37h0a44026_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py37_1
  - panel=0.9.5=py_1
  - param=1.9.3=py_0
  - parso=0.7.0=py_0
  - partd=1.1.0=py_0
  - pexpect=4.8.0=py37_0
  - phantomjs=2.1.1=1
  - pickleshare=0.7.5=py37_0
  - pillow=7.1.2=py37h4655f20_0
  - pip=20.0.2=py37_1
  - prometheus_client=0.7.1=py_0
  - prompt-toolkit=3.0.4=py_0
  - prompt_toolkit=3.0.4=0
  - psutil=5.7.0=py37h1de35cc_0
  - ptyprocess=0.6.0=py37_0
  - pycparser=2.20=py_0
  - pyct=0.4.6=py37_0
  - pygments=2.6.1=py_0
  - pyopenssl=19.1.0=py37_0
  - pyparsing=2.4.7=py_0
  - pyrsistent=0.16.0=py37h1de35cc_0
  - pysocks=1.7.1=py37_0
  - python=3.7.7=hc70fcce_0_cpython
  - python-dateutil=2.8.1=py_0
  - python-snappy=0.5.4=py37h0a44026_0
  - pytz=2019.3=py_0
  - pyviz_comms=0.7.4=py_0
  - pywavelets=1.1.1=py37h1de35cc_0
  - pyyaml=5.3.1=py37h1de35cc_0
  - pyzmq=18.1.1=py37h0a44026_0
  - readline=8.0=h1de35cc_0
  - requests=2.23.0=py37_0
  - rise=5.6.1=py37_0
  - scikit-image=0.16.2=py37h6c726b0_0
  - scipy=1.4.1=py37h9fa6033_0
  - selenium=3.141.0=py37h1de35cc_0
  - send2trash=1.5.0=py37_0
  - setuptools=46.1.3=py37_0
  - six=1.14.0=py37_0
  - snappy=1.1.7=he62c110_3
  - sortedcontainers=2.1.0=py37_0
  - sqlite=3.31.1=h5c1f38d_1
  - streamz=0.5.2=py_0
  - tbb=2020.0=h04f5b5a_0
  - tblib=1.6.0=py_0
  - terminado=0.8.3=py37_0
  - testpath=0.4.4=py_0
  - thrift=0.13.0=py37h0a44026_0
  - tk=8.6.8=ha441bb4_0
  - toolz=0.10.0=py_0
  - tornado=6.0.4=py37h1de35cc_1
  - tqdm=4.45.0=py_0
  - traitlets=4.3.3=py37_0
  - typing_extensions=3.7.4.1=py37_0
  - urllib3=1.25.8=py37_0
  - wcwidth=0.1.9=py_0
  - webencodings=0.5.1=py37_1
  - wheel=0.34.2=py37_0
  - widgetsnbextension=3.5.1=py37_0
  - xarray=0.11.3=py37_0
  - xz=5.2.5=h1de35cc_0
  - yaml=0.1.7=hc338f04_2
  - zeromq=4.3.1=h0a44026_3
  - zict=2.0.0=py_0
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h1de35cc_3
  - zstd=1.3.7=h5bba6e5_0
prefix: /opt/anaconda3/envs/holoviz-tutorial

